Fixed bug: can't set duration higher than width of shell size
edouard-lopez/progress-bar.sh pull request #7
Opened 2019-02-01 09:21 UTC by scheleon

I was not able to set the duration higher than the shell size, so I introduced a new variable factor and now the bar fills accordingly( bar fills from done=0;done <(elapsed/factor)).

2019-02-01 12:03 UTC, edouard-lopez approved these changes
Thanks for the PR

2019-02-01 12:03 UTC, edouard-lopez commented on progress-bar.sh
> +#!usr/bin/env bash
This is incorrect, you need a valid path for [shebang](https://stackoverflow.com/a/10383546/802365)

2019-02-01 12:03 UTC, edouard-lopez commented on progress-bar.sh
> +  local columns=$(tput cols)
Should be done in two steps (cf. [Shellcheck SC2155](https://github.com/koalaman/shellcheck/wiki/SC2155)):

Could you do the same for `duration` and `spaceAvailable`?

```bash
  local duration
  local columns
  local spaceAvailable

  duration=${1}
  columns=$(tput cols)
  spaceAvailable=$((columns-5))
```

2019-02-01 12:03 UTC, edouard-lopez commented on progress-bar.sh
> +  if (( duration <= spaceAvailable )); then factor=1;
```suggestion
  if (( duration <= space_available )) then fit_to_screen=1; else fit_to_screen=$(( duration / space_available )); fi

```

2019-02-01 12:03 UTC, edouard-lopez commented on progress-bar.sh
> +  local spaceAvailable=$((columns-5))
Good naming :+1:

However, as per [Google Style Guide naming convention](https://google.github.io/styleguide/shell.xml#Naming_Conventions), please use `snake_case`: 

    space_available

2019-02-01 12:03 UTC, edouard-lopez commented on progress-bar.sh
> +  else factor=$((duration/spaceAvailable));
Bash only does integer division:

```bash
$ echo $((4/2))
2
$ echo $((4/3))
1
```

2019-02-01 12:12 UTC, edouard-lopez requested changes
I did a review, but I got a new line for each step with your code.
![progress-bar](https://user-images.githubusercontent.com/1212392/52120556-f00f8700-261c-11e9-80f5-3719fa4fcff6.gif)

Also, you need to rebase on master as I added some tests

2019-02-01 18:40 UTC, scheleon commented
I made some changes and its working fine, no new line, but still its unable to erase the entire last line when completed 100%.

2019-02-01 21:59 UTC, edouard-lopez requested changes
That look nice!
Could you update based on my review, I will merge next week as I won't be available in the coming days.

2019-02-01 21:59 UTC, edouard-lopez commented on progress-bar.sh
> +  space_available=$(( columns-10 ))
could you replace the magic number `10` by an explicit variable name?

2019-02-01 21:59 UTC, edouard-lopez commented on progress-bar.sh
> +  if (( duration < space_available )); then fit_to_screen=1; else fit_to_screen=$(( duration / space_available )); fit_to_screen=$(( fit_to_screen + 1 )); fi
better spread on several lines for readability.

2019-02-02 03:32 UTC, shubhamkumar-revefi commented
I did a quick review and have updated the file. Thanks for the help and support. I would appreciate any advice or suggestions for the future.

2019-02-05 22:23 UTC, edouard-lopez commented on progress-bar.sh
> +  space_reserved=10   # reserved width for the percentage value
`6` characters are enough

2019-02-05 22:46 UTC, edouard-lopez approved these changes

2019-02-05 23:16 UTC, merged